database: mysql

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&user=${DB_USER}&password=${DB_PASS}&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=5
    username: ${DB_USER}
    password: ${DB_PASS}
    properties:
      hibernate:
        format_sql: true
  cloud:
    gcp:
      sql:
        enabled: false
        database-name: ${DB_NAME}
        instance-connection-name: ${INSTANCE_CONNECTION_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode:
        always


security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4fyWNKtW7VXv+MEzKh1G/fNepuRcnm+3z0WFu8pclKtFcPc4xu11zUki4XmspdNnDhGLA4+jX4GLV0F5QuoH8gl7J/vaBnd4rjWyxYKLXcn1gsTZmp/+34e7/dsZKZMsXP2tnzqCJ3Jdk6qhjUxc6zgGIkJrd/9oVlJb7flb/LG6ZEwLJtaBllNHnuAwS7fsVTvdeh6evIb0ZATp934f/siauZ9QObH7eMcBusfk/e7r1BS2XlJz+/lt5woMaczusEFCPmGL9Rc5IKhkr5RTBCbSEqb0HyWgoMDCPWFSeVVlqUyPfQopvGGZNbqx1qLc64np/mR05zPSKDCKozUAowIDAQAB-----END PUBLIC KEY-----

server:
  port: 8082


