apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourceserver
spec:
  selector:
    matchLabels:
      app: resourceserver-app
  template:
    metadata:
      labels:
        app: resourceserver-app
    spec:
      # For more information about using Kubernetes service accounts see:
      # https://cloud.google.com/kubernetes-engine/docs/how-to/kubernetes-service-accounts
      serviceAccountName: ksa-cloud-sql # TODO(developer): replace this value.
      containers:
        - name: resourceserver-app
          # Replace <LOCATION> with your Artifact Registry location (e.g., us-central1).
          # Replace <YOUR_PROJECT_ID> with your project ID.
          image: us-central1-docker.pkg.dev/burner-shin1/resourceserver/gke-sql:latest
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: INSTANCE_CONNECTION_NAME
              value: burner-shin1:us-central1:shilpa-test
            - name: DB_HOST
              value: "34.69.207.243"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: database